### ISSUE TITLE
can't write if/else operator 

### ISSUE THREAD

**Issue by al-zatv** [ninjaaron/pyfil#4]
Hello! I have found this brilliant tool, and now using it more and more.  Now I want to write if/else operator (not ternary operator), but can't find right syntax. For example:

`ls -1 -F | pyfil -l -x "if i[-1]=='/': os.not_rmdir(i); else: os.not_remove(i)"`

But, it is an error:
`  File "/usr/local/lib/python3.5/dist-packages/pyfil.py", line 253, in <listcomp>
    '<string>', func) for e in a.expression]
  File "<string>", line 1
    if i[-1]=='/': os.not_rmdir(i); else: os.not_remove(i)
                                       ^
SyntaxError: invalid syntax
`

How can I do it?
If it is impossible now, may be we can enhance the syntax with something like '>' sign, with meaning 'one level of indent'? For example:

pyfil -x 'def qabs(x):' '>if x>=0:' '>>return x' '>else:'  '>>return -x'  'fabs(100)'

**Comment by ninjaaron** [comment]
Hi! I'm glad you like pyfil. The example you give would work with the ternary operator, but I guess you're looking to do something a little more complex.

One "feature" of pyfil is that it doesn't modify or transform Python syntax in any way. What you see is what you get. Even the dot syntax for accessing dictionary keys from de-serialized JSON is supplied at runtime by a special class. I am hesitant to change this precedent. (... don't cross-examine this contention with regard to exception handling...)

Another concern is that I'm not sure the added complexity in the code-base necessary to support structured programming would be worth the payoff. My thought up to this point has been that, if you need structured programming, it's probably time to start putting code in a file.

I'm willing to hear arguments to the contrary, but let's just say it's going to take a lot of convincing!

**Comment by al-zatv** [comment]
> One "feature" of pyfil is that it doesn't modify or transform Python syntax in any way.

I agree that it is a big plus of pyfil. So, let's look at my suggestion having this feature in mind. Let say I want to define a function 
```
def qabs(x):
   if x>=0: return x
   else: return -x
```

Let's simply rewrite it line-by-line: 
`pyfil -x2 "def qabs(x):" "  if x>=0: return x" "   else: return -x"    "print(qabs(-100))"`

Voila, we can write as powerfull one-liners as we want, and we didn't change python's syntax. What do you think about it?

**Comment by al-zatv** [comment]
> My thought up to this point has been that, if you need structured programming, it's probably time to start putting code in a file.

As for time to start putting code to a file, you are right,of course. But sometimes it is better to have one-liner, so it can be nice to have a flexibility here.

> Another concern is that I'm not sure the added complexity in the code-base necessary to support structured programming would be worth the payoff. 

Your concern is have sense,of course. May be, if implement it like in comment https://github.com/ninjaaron/pyfil/issues/4#issuecomment-568214391 (actually without special syntax) it will be less complexity for code base?

**Comment by ninjaaron** [comment]
I think that is reasonable. I'll give it a shot.

**Comment by ninjaaron** [comment]
Ok, I didn't actually ever get on this, but I just was thinking about it again and it occurred to me that it should mostly already work.

```shell
$ ls | pyfil -x '
for p in map(pathlib.Path, stdin):
    if p.is_dir():
        print(p, "is a directory")
'
```
The `-x` flag allows embedding arbitrary Python code. My opinion is that, if you want to use Python blocks, it's actually much cleaner to just do it in a single multi-line string than to make each line a separate command line argument. Thoughts?

**Comment by al-zatv** [comment]
> My opinion is that, if you want to use Python blocks, it's actually much cleaner to just do it in a single multi-line string than to make each line a separate command line argument. Thoughts?

Sounds reasonable. I will try this approach on closest ocassion.
