### ISSUE TITLE
bug with attribute 'Iterator' on python3.10 (which is default in ubuntu 22.04)

### ISSUE THREAD

**Issue by al-zatv** [ninjaaron/pyfil#9]
Error:
'''
$ pyfil -j j < tt.json > tt.pretty.json 
Traceback (most recent call last):
  File "/home/al/bin/pyfil", line 8, in <module>
    sys.exit(main())
  File "/home/al/.local/lib/python3.10/site-packages/pyfil.py", line 298, in main
    run(expressions, a, namespace)
  File "/home/al/.local/lib/python3.10/site-packages/pyfil.py", line 171, in run
    elif isinstance(value, collections.Iterator):
AttributeError: module 'collections' has no attribute 'Iterator'
'''
Probably, it's because of python3.10, which is installed by default on Ubuntu 22.04:
'''
$ python3
Python 3.10.4 (main, Apr  2 2022, 09:04:19) [GCC 11.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> 
'''

**Comment by raddessi** [comment]
From looking this over a bit it seems like the module would need a slight overhaul to support python 3.10 unfortunately :/

**Comment by ninjaaron** [comment]
Thanks for reporting this bug! I have fixed the bug with `collections.Iterator` in master. I'm using 22.04 myself now, and pyfil appears to be working, but let me know if you find any more issues!
